// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcOMKIzerd3EmhgcZjEPweiBxlkjxaQyE',
    appId: '1:1012270224526:web:0bcd7862fa49254c8565df',
    messagingSenderId: '1012270224526',
    projectId: 'pard-13191',
    authDomain: 'pard-13191.firebaseapp.com',
    storageBucket: 'pard-13191.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVde-Mf88ZIB5I6su8eZdG8tvCwYG3bYA',
    appId: '1:1012270224526:android:0964d3eb2d81fa2f8565df',
    messagingSenderId: '1012270224526',
    projectId: 'pard-13191',
    storageBucket: 'pard-13191.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8qnyn_sTH0iSTmGhS14zOwj-F0_S87Lo',
    appId: '1:1012270224526:ios:83b98d5fb46e46118565df',
    messagingSenderId: '1012270224526',
    projectId: 'pard-13191',
    storageBucket: 'pard-13191.appspot.com',
    iosClientId: '1012270224526-qovq944cahqsdpibo2644mebj2762d3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8qnyn_sTH0iSTmGhS14zOwj-F0_S87Lo',
    appId: '1:1012270224526:ios:83b98d5fb46e46118565df',
    messagingSenderId: '1012270224526',
    projectId: 'pard-13191',
    storageBucket: 'pard-13191.appspot.com',
    iosClientId: '1012270224526-qovq944cahqsdpibo2644mebj2762d3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );
}
