name: idih
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

assets:
  - assets/images/

fonts:
  - family: AppleSDGothicNeo
    fonts:
      - asset: assets/fonts/AppleSDGothicNeoR.ttf
  - family: NanumGothic
    fonts:
      - asset: assets/fonts/NanumGothic.ttf
  - family: NanumSqaureNeo
    fonts:
      - asset: assets/fonts/NanumSquareNeoOTF-Rg.otf
  - family: NotoSansMonoCJK
    fonts:
      - asset: assets/fonts/NotoSansMonoCJKkr-Regular.otf

dependencies:
  cloud_firestore: ^4.7.1
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
